- base
- linux
- linux-firmware
- sudo
- networkmanager
- openssh
- grub
- efibootmgr
- os-prober
- btrfs-progs
- dosfstools
- e2fsprogs
- lvm2
- ntfs-3g
- gptfdisk
- smartmontools
- testdisk
- gparted
- rsync
- timeshift
- refind-efi
- xfce4
- xfce4-goodies
- lightdm
- lightdm-gtk-greeter
- xorg-server
- xorg-xinit
- pipewire
- pipewire-alsa
- pipewire-pulse
- pavucontrol
- firefox
