---
dontChroot: false
timeout: 120
verbose: true
script:
  - "-/usr/bin/userdel --remove liveuser"
  - "-/usr/bin/rm -f /etc/sudoers.d/10-liveuser"
  - "-/usr/bin/rm -f /etc/polkit-1/rules.d/49-live-calamares.rules"
  - "-/usr/bin/rm -f /etc/sddm.conf.d/10-live-autologin.conf"
  - "-/usr/bin/rm -rf /etc/calamares"
  - "-/usr/bin/rm -rf /usr/local/lib/arch-calam"
  - "-/usr/bin/rm -f /etc/pacman.d/hooks/90-arch-calam-live.hook"
  - "-/usr/bin/rm -f /etc/skel/Desktop/install-arch.desktop"
  - "-/usr/bin/rm -f /usr/share/applications/install-arch.desktop"
  - "-/usr/bin/rm -f /etc/ssh/sshd_config.d/10-archiso.conf"
  - "-/usr/bin/rm -f /etc/motd"
  - "-/usr/bin/rm -rf /etc/systemd/journald.conf.d/volatile-storage.conf"
  - "-/usr/bin/rm -rf /etc/systemd/logind.conf.d/do-not-suspend.conf"
  - "-/usr/bin/rm -rf /etc/systemd/network"
  - "-/usr/bin/rm -rf /etc/systemd/networkd.conf.d"
  - "-/usr/bin/rm -rf /etc/systemd/resolved.conf.d/archiso.conf"
  - "-/usr/bin/rm -f /etc/systemd/system/choose-mirror.service"
  - "-/usr/bin/rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"
  - "-/usr/bin/rm -f /etc/systemd/system/livecd-alsa-unmuter.service"
  - "-/usr/bin/rm -f /etc/systemd/system/livecd-talk.service"
  - "-/usr/bin/rm -f /etc/systemd/system/pacman-init.service"
  - "-/usr/bin/rm -f /root/.automated_script.sh /root/.zlogin"
  - "-/usr/bin/rm -rf /root/.gnupg"
  - "-/usr/bin/rm -f /usr/local/bin/choose-mirror"
  - "-/usr/bin/rm -f /usr/local/bin/Installation_guide"
  - "-/usr/bin/rm -f /usr/local/bin/livecd-sound"
i18n:
  name: "Remove live-session configuration"
