---
backend: pacman
skip_if_no_internet: false
update_db: false
ignore_update_db_error: true
update_system: false
pacman:
  num_retries: 0
  disable_download_timeout: false
  needed_only: true
operations:
  - try_remove:
      - calamares
      - archiso
      - archinstall
      - cloud-init
      - livecd-sounds
      - mkinitcpio-archiso
      - ckbcomp
      - syslinux
