partition:
  defaultFileSystemType: ext4
  availableFileSystemTypes:
    - ext4
    - btrfs
  initramfs: mkinitcpio
  efiBootLoader: systemd-boot
  bootLoader: grub
  dontUseMbr: false
  alwaysShowPartitioningOptions: true
  drawNestedPartitions: true
  allowManualPartitioning: true
  choicePage:
    defaultOption: replace
    partitionModes:
      - replace
      - alongside
      - manual
      - erase
  filesystemChecks:
    - ext4
    - btrfs
  ensureSuspendToDisk: false
  allowPreexisting: true
