---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 1GiB
  minimumSize: 300MiB
  label: "EFI"

userSwapChoices: [ none, small, suspend, file ]
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4", "btrfs" ]
allowManualPartitioning: true
alwaysShowPartitionLabels: true
drawNestedPartitions: true
luksGeneration: luks1
enableLuksAutomatedPartitioning: true
essentialMounts: [ "live-*", "control", "ventoy" ]
lvm:
  enable: true

directoryFilesystemRestrictions:
  - directory: "/"
    allowedFilesystemTypes: [ "ext4", "btrfs" ]
  - mountpoint: "efi"
    allowedFilesystemTypes: [ "fat32" ]
    onlyWhenMountpoint: true
