---
dontChroot: false
timeout: 30
verbose: true
script:
  - "/usr/bin/install -m 0644 /usr/local/lib/arch-calam/linux.preset /etc/mkinitcpio.d/linux.preset"
  - "-/usr/bin/rm -f /etc/mkinitcpio.conf.d/archiso.conf"
i18n:
  name: "Configure the installed kernel"
