---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - wheel
  - audio
  - video
  - storage
  - network
  - lp
sudoersGroup: wheel
sudoersConfigureWithGroup: true
setRootPassword: true
doReusePassword: true
displayAutologin: true
doAutologin: false
passwordRequirements:
  minLength: 8
  maxLength: 128
allowWeakPasswords: true
allowWeakPasswordsDefault: false
user:
  shell: /bin/bash
  forbidden_names: [ root, liveuser ]
  home_permissions: "o700"
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "archlinux"
  forbidden_names: [ localhost, archiso ]
allowActiveDirectory: false
