modules-search: [/etc/calamares/modules]
instances:
  - id: default
    name: default
sequence:
  - show:
      - welcome
  - exec:
      - locale
      - keyboard
      - partition
      - users
      - displaymanager
      - services
      - packages
      - fstab
      - finished
branding: arch-calam
prompt-install: false
disable-cancel-during-exec: true
