---
modules-search: [ local ]

instances:
  - id: preparetarget
    module: shellprocess
    config: preparetarget.conf
  - id: cleanup
    module: shellprocess
    config: cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - shellprocess@preparetarget
      - initcpiocfg
      - initcpio
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - packages
      - shellprocess@cleanup
      - bootloader
      - umount
  - show:
      - finished

branding: arch
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
